spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:34569/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=oIuRXXrPHSzMAJtbrswKByewKefAOxwd

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true